-- The morning practice, and the one part of it that stops at a decision only the owner can make.
--
-- WHAT THE SPIRIT SCREEN WAS. Moon phase, illumination percentage, a contribution counter, an
-- almanac. All correct, all computed, and none of it anything to DO. Her §8.1 says Spirit is an
-- active operating pillar that "must be rendered explicitly in the daily agenda", and the daily
-- agenda was rendering the sky instead.
--
-- Most of the fix needs no schema at all: §8.3's seven-step sequence and §8.4's floor are fixed in
-- her contract and belong in code, and §6.9's movement contract was already being computed and
-- simply never shown. This migration exists for the one piece that ran into a wall.
--
-- ─── The gratitude sentence, and why there is no table for it ────────────────
--
-- TWO OF THE OWNER'S OWN RULES POINT OPPOSITE WAYS, AND THIS IS NOT MINE TO SETTLE.
--
--   §8.5 and her instruction in plain words: one exact sentence every morning, and "the user should
--   not have to invent it" — she said the LLM writes it daily.
--
--   Her classification: `spirit` is a SOVEREIGN SUBSYSTEM. Every table in it is LOCAL_ONLY on both
--   axes, which means spirit material may not be stored outside the private domain AND may not be
--   reasoned about by any cloud model. `scripts/validate/data-classification.mjs` enforces this at
--   build time precisely so it cannot be softened inside a long SQL diff.
--
-- A gratitude sentence written by Workers AI is spirit material reaching a cloud model. There is no
-- reading of the sovereignty rule that permits it, and the only ways through are her word or the
-- local runtime she has deferred.
--
-- SO THIS IS A NAMED STOP, NOT A LOOSENING. The entity is classified, the airlock governs it, and
-- it has no table: nothing about her gratitude is written into Cloudflare's database while the
-- question is open. The screen says what it is waiting for. The alternative — adding `spirit` to
-- the exceptions list so the feature could ship today — is exactly the "classify it in whatever
-- direction unblocks the demo" that the validator was written to prevent, and it would have
-- traded a sovereignty guarantee for one sentence.
--
-- Both axes are LOCAL_ONLY because that is what the subsystem is. When the local runtime exists it
-- satisfies this as written, with no change here at all.
INSERT INTO data_policy (entity, subsystem, residency, ai_processing, reason) VALUES
  ('gratitude_sentences', 'spirit', 'LOCAL_ONLY', 'LOCAL_ONLY',
   'One sentence a day, to be spoken out loud, drawn from her real life - which makes it spirit material, and spirit is sovereign on both axes. It is never stored in the cloud domain and no cloud model may write it. Her instruction that an LLM produces it daily and her classification of spirit as sovereign genuinely conflict; the screen names the stop rather than resolving it in either direction. The local runtime satisfies this as written.')
ON CONFLICT(entity) DO NOTHING;

-- The reasoning, in the log kept for exactly this, so a reader a year from now finds the decision
-- rather than inferring it from an absence.
INSERT INTO policy_change_log (id, entity, from_residency, to_residency, from_ai, to_ai, reason, changed_by)
VALUES ('pcl_gratitude_0179', 'gratitude_sentences', NULL, 'LOCAL_ONLY', NULL, 'LOCAL_ONLY',
  'Classified sovereign because `spirit` is a sovereign subsystem and this is spirit material. NOT loosened to let the daily sentence be generated by Workers AI, which is what shipping the feature today would have required. The owner asked for an LLM-written gratitude sentence AND classified spirit as local-only on both axes; those cannot both hold, and reclassifying her sovereign material to resolve it is not a decision an implementation gets to make. Awaiting her word, or the local runtime (Batch 2).',
  'boss');

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0179_boss_daily_practice');
